export class D3DirectedGraphConfig {
  static CONNECTION_ERROR_STROKE_COLOR = '#d9534f';
  static CONNECTION_CHANGING_STROKE_COLOR = '#546f7d';
  static CONNECTION_ACTIVE_STREAM_COLOR = '#5bc0de';
  static CONNECTION_IDLE_STREAM_COLOR = '#4b0082';

  static CONNECTION_OPENING_STROKE_DASH = [8, 8];
  static CONNECTION_CLOSING_STROKE_DASH = [2, 8];

  static NODE_STREAMER_FILL_COLOR = '#4682B4';
  static NODE_ROLE_SIGNAL_FILL_COLOR = '#f83d51';
  static NODE_ROLE_ROUTER_FILL_COLOR = '#07cc55';
  static NODE_ROLE_NEWBIE_FILL_COLOR = '#ffd4b8';
}
